apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: '{{app}}'
  namespace: '{{namespace}}'
  labels:
    app: '{{app}}'
    process: '{{process}}'
  annotations:
    kubernetes.io/ingress.class: nginx
{{#if tplSessionAffinity}}
    # See https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#session-affinity
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
{{/if}}
{{#if tplExpandedTimeout}}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{tplExpandedTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timout: "{{tplExpandedTimeout}}"
{{/if}}
spec:
  rules:
  - host: '{{app}}.{{domain}}'
    http:
      paths:
      - backend:
          serviceName: '{{app}}'
          servicePort: 80
